routes:
    home: 'Default:home'
    about: 'Default:about'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    createArticle: 'Article:createArticle'
    showArticle: 'Article:showArticle'

defaut_route: 'home'

db_config:
    name: 'blog_project'
    host: 'localhost'
    user: 'root'
    pass: ''
